### ISSUE TITLE
JXA support?

### ISSUE THREAD

**Issue by hmijail** [rdhyee/py-applescript#14]
JXA is not mentioned anywhere and I'm not good at any of the used languages/frameworks to check myself, so I thought I'd ask. Is JXA supported? 

If not please consider this a Feature Request :)

**Comment by rdhyee** [comment]
@hmijail As far as I can tell, JXA is still supported (https://apple.stackexchange.com/questions/405061/is-jxa-still-supported). This project is about using Python as a substitute for AppleScript. JXA serves an analogous role for JavaScript. I don't understand what it'd mean for this project to support JXA.

**Comment by hmijail** [comment]
Sorry, I think I wasn't clear. What I meant to ask was whether it's possible to do something similar to this with py-applescript:
```
applescript.JXA('Application("Music").playpause()').run()
```

In other words: can I provide a script written in JXA instead of AppleScript?

**Comment by hmijail** [comment]
After exploring elsewhere the status and story of JXA, AppleScript, bridges... looks like trying to use JXA is the worst option. I'll stick to AppleScript if anything.
