### ISSUE TITLE
No license file present in repo

### ISSUE THREAD

**Issue by ndmaxar** [rdhyee/py-applescript#5]

**Comment by RhetTbull** [comment]
Note the README states "py-applescript is released into the public domain. No warranty; use at own risk, etc.".  As this is not enforceable in all jurisdictions, agree it would be good for the author to attach a license of some kind.  [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/) seems like an OSF compliant "Public Domain" compatible license.

**Comment by rdhyee** [comment]
Thank you @RhetTbull for making it easy for me to fix this issue and to @ndmaxar for reporting this problem.
