### ISSUE TITLE
Required pyobjc dependency can be reduced to only a few

### ISSUE THREAD

**Issue by mhucka** [rdhyee/py-applescript#7]
`setup.py` currently [requires `pyobj`](https://github.com/rdhyee/py-applescript/blob/9cfae75e05b6727bcc4f76c88a2d4e353b38c124/setup.py#L13), but it does not appear to need _all_ of `pyobjc`. It only appears to need the following:

```
pyobjc-core
pyobjc-framework-AppleScriptKit
pyobjc-framework-AppleScriptObjC
```

If this is correct, it would be beneficial to change `setup.py` to limit what it requires. The downside of doing a blanket `pyobjc` requirement is not only that it is relatively time-consuming installation step: there is at least one package (`pyobjc-framework-PubSub`) that ends up conflicting with a Python package (`pypubsub`) because both install files into `site-packages/PubSub`.

**Comment by glyph** [comment]
I translated this into a really simple PR, although I haven't tested this to see if it causes problems :)

**Comment by rdhyee** [comment]
@mhucka @glyph Thanks for reporting this issue and translating the issue into a PR. I'm sorry that I just noticed this PR. I'll take a look at it this weekend.
